# Generated by Django 6.1.1 on 2026-09-07 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEO', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_categoria', models.CharField(max_length=100, unique=True)),
                ('limite_max_itens', models.PositiveIntegerField(default=1)),
                ('prazo_dias', models.PositiveIntegerField(default=7)),
            ],
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_solicitacao', models.DateTimeField(auto_now_add=True)),
                ('data_expiracao', models.DateTimeField()),
                ('cg_validacao', models.CharField(max_length=10, unique=True)),
                ('status_geral', models.CharField(choices=[('PENDENTE', 'Pendente de Retirada'), ('ATIVO', 'Ativo/Em Andamento'), ('CONCLUIDO', 'Concluído'), ('EXPIRADO', 'Expirado (Não retirado)'), ('CANCELADO', 'Cancelado')], default='PENDENTE', max_length=15)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='emprestimos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Objeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cg_patrimonio', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('nome_objeto', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('DISPONIVEL', 'Disponível'), ('EMPRESTADO', 'Emprestado'), ('MANUTENCAO', 'Em Manutenção'), ('INATIVO', 'Inativo')], default='DISPONIVEL', max_length=15)),
                ('condicao', models.CharField(choices=[('INTEGRO', 'Íntegro/Perfeito'), ('AVARIADO', 'Com Avaria')], default='INTEGRO', max_length=15)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objetos', to='SIGEO.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao_prevista', models.DateTimeField()),
                ('data_devolucao_real', models.DateTimeField(blank=True, null=True)),
                ('status_item', models.CharField(choices=[('AGUARDANDO_RETIRADA', 'Aguardando Retirada'), ('COM_USUARIO', 'Com o Usuário'), ('DEVOLVIDO', 'Devolvido'), ('ATRASADO', 'Em Atraso')], default='AGUARDANDO_RETIRADA', max_length=20)),
                ('condicao_retorno', models.CharField(blank=True, max_length=15, null=True)),
                ('emprestimo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='SIGEO.emprestimo')),
                ('objeto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historico_emprestimos', to='SIGEO.objeto')),
            ],
        ),
    ]
