# Generated by Django 6.1.1 on 2026-09-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SIGEO', '0002_categoria_emprestimo_objeto_itememprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimo',
            name='cg_validacao',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='codigo_devolucao',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='codigo_retirada',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
